version: '3'
services:
  pi-image-builder:
    container_name: pi-image-builder
    image: pi-image-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_HOSTNAME: ${IMAGE_HOSTNAME:-raspberrypi}
    volumes:
      - ./images/:/output/
